import { Exercise } from "../core/models/exercises.interface";

export const listOfExercises : Omit<Exercise, 'amount'>[]= [
    { id: 1, name: 'Press Banca', zona: 'pectoral' },
    { id: 2, name: 'Press Banca Inclinado', zona: 'pectoral' },
    { id: 3, name: 'Press Banca Declinado', zona: 'pectoral' },
    { id: 4, name: 'Press con Mancuernas', zona: 'pectoral' },
    { id: 5, name: 'Press Inclinado con Mancuernas', zona: 'pectoral' },
    { id: 6, name: 'Aperturas con Mancuernas', zona: 'pectoral' },
    { id: 7, name: 'Aperturas en Contractor de pectoral', zona: 'pectoral' },
    { id: 8, name: 'Fondos en Paralelas (enfocado en pectoral)', zona: 'pectoral' },
    { id: 9, name: 'Flexiones (Push Ups)', zona: 'pectoral' },
    { id: 10, name: 'Press en Máquina', zona: 'pectoral' },
    { id: 11, name: 'Press Hammer', zona: 'pectoral' },
    { id: 12, name: 'Crossover en Polea', zona: 'pectoral' },
    { id: 13, name: 'Dominadas', zona: 'espalda' },
    { id: 14, name: 'Jalón al Pecho en Polea', zona: 'espalda' },
    { id: 15, name: 'Remo con Barra', zona: 'espalda' },
    { id: 16, name: 'Remo con Mancuerna', zona: 'espalda' },
    { id: 17, name: 'Remo en Máquina Hammer', zona: 'espalda' },
    { id: 18, name: 'Peso Muerto', zona: 'espalda' },
    { id: 19, name: 'Remo en Polea Baja', zona: 'espalda' },
    { id: 20, name: 'Pull Over en Polea', zona: 'espalda' },
    { id: 21, name: 'Curl con Barra', zona: 'biceps' },
    { id: 22, name: 'Curl con Mancuernas', zona: 'biceps' },
    { id: 23, name: 'Curl Alterno en Supinación', zona: 'biceps' },
    { id: 24, name: 'Curl Concentrado', zona: 'biceps' },
    { id: 25, name: 'Curl en Predicador', zona: 'biceps' },
    { id: 26, name: 'Curl en Polea Baja', zona: 'biceps' },
    { id: 27, name: 'Curl Martillo', zona: 'biceps' },
    { id: 28, name: 'Fondos en Paralelas', zona: 'triceps' },
    { id: 29, name: 'Extensión de Tríceps en Polea', zona: 'triceps' },
    { id: 30, name: 'Press Francés con Barra Z', zona: 'triceps' },
    { id: 31, name: 'Extensión con Mancuerna a una Mano', zona: 'triceps' },
    { id: 32, name: 'Extensión en Polea Alta con Cuerda', zona: 'triceps' },
    { id: 33, name: 'Press Cerrado con Barra', zona: 'triceps' },
    { id: 34, name: 'Crunch Abdominal', zona: 'abdomen' },
    { id: 35, name: 'Elevación de Piernas', zona: 'abdomen' },
    { id: 36, name: 'Plancha', zona: 'abdomen' },
    { id: 37, name: 'Crunch Invertido', zona: 'abdomen' },
    { id: 38, name: 'Abdominal en Máquina', zona: 'abdomen' },
    { id: 39, name: 'Toques de Talón (Heel Touches)', zona: 'abdomen' },
    { id: 40, name: 'Crunch con Polea Alta', zona: 'abdomen' },
    { id: 41, name: 'Press Militar con Barra', zona: 'hombros' },
    { id: 42, name: 'Press con Mancuernas', zona: 'hombros' },
    { id: 43, name: 'Elevaciones Laterales', zona: 'hombros' },
    { id: 44, name: 'Elevaciones Frontales', zona: 'hombros' },
    { id: 45, name: 'Pájaros (Elevaciones Posteriores)', zona: 'hombros' },
    { id: 46, name: 'Remo al Mentón', zona: 'hombros' },
    { id: 47, name: 'Press Arnold', zona: 'hombros' },
    { id: 48, name: 'Elevación de Talones de Pie', zona: 'pantorrillas' },
    { id: 49, name: 'Elevación de Talones Sentado', zona: 'pantorrillas' },
    { id: 50, name: 'Elevación de Talones en Prensa', zona: 'pantorrillas' },
    { id: 51, name: 'Saltos con Peso', zona: 'pantorrillas' },
    { id: 52, name: 'Sentadillas', zona: 'piernas' },
    { id: 53, name: 'Prensa de Piernas', zona: 'piernas' },
    { id: 54, name: 'Peso Muerto Rumano', zona: 'piernas' },
    { id: 55, name: 'Zancadas (Lunges)', zona: 'piernas' },
    { id: 56, name: 'Curl Femoral', zona: 'piernas' },
    { id: 57, name: 'Extensiones de Pierna', zona: 'piernas' },
    { id: 58, name: 'Sentadillas Búlgaras', zona: 'piernas' },
    { id: 59, name: 'Hip Thrust', zona: 'piernas' }
]